In [2]:
import re
import operator
import numpy as np
from scipy import spatial as sp

In [3]:
file = open('sent.txt', 'r')
lines = (sum(1 for line in open('sent.txt', 'r'))) # подсчитываем колличество строк
# считываем файл в строки, приводя к нижнему регистру,
# проводим токенезацию,
# удаляем пробельные элементы
file = file.read().lower()
fileList = re.split('[^a-z]', file)
fileList = [x for x in fileList if x]

# добавляем в словарь неповторяющиеся эементы,
# делаем копию словаря
words = {}
number = 0
for x in fileList:
    if x not in words:
        words[x] = number
        number += 1

copyWords = words.copy()

# обнуляем значения первого словаря,
# чтобы подсчитать колличество 
# повторений слова в тексте
for x in words:
    words[x] = 0
for x in fileList:
    for y in words:
        if y == x:
            words[y] += 1

matrix = np.zeros((lines, number), 'int')

for x in copyWords:
    m = 0
    for line in open('sent.txt', 'r'):
        line = line.lower()
        token = re.split('[^a-z]', line)
        matrix[m][copyWords[x]] = token.count(x)
        m += 1
print(matrix)
#считаем косинусное расстоняие
res = {}
for n in range(lines):
    answ = round((sp.distance.cosine(matrix[0],matrix[n])), 2)
    res[n] = answ

# сортировка по значению
res = sorted(res.items(), key=operator.itemgetter(1))

# два наиболее похожих предложения на первое
first = res[1]
second = res[2]

print(res)

[[1 1 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [0 0 1 ... 1 1 1]]
[(0, 0.0), (6, 0.73), (4, 0.78), (10, 0.83), (21, 0.83), (12, 0.84), (16, 0.84), (20, 0.84), (2, 0.86), (13, 0.87), (14, 0.87), (8, 0.88), (11, 0.88), (19, 0.89), (3, 0.9), (9, 0.91), (7, 0.93), (5, 0.94), (15, 0.94), (18, 0.94), (1, 0.95), (17, 0.96)]
